### ISSUE TITLE
redirection 테스트 중 이슈

### ISSUE THREAD

**Issue by Two-Jay** [AYoungSn/webServ_42#5]
1. ConfigParsing 시 문자열 기반 주소는 취급 안했는데, "localhost"의 경우는 되더군요. 예를들어 아래의 서버 설정은 유효합니다.

`server {
    listen localhost:8000
    return 301 https://youtube.com/
}`

2. Config 의 신텍스 추가도 해야됨. (NGINX 기준..)
    - 한 라인의 끝은 ';'까지.
    - 주석은 '#' 이 있는 시점부터 이후 해당라인 문자열 끝까지 (파싱 시작시 '#'찾고 삭제해버리면 됨)
    
3. 만들어 놓은 response 객체의 append_header를 쓰고 있는데, 내부 구조체가 map 이라 넣는 순서에 따라 순서 보장이 안됩니다.

response.append_header("Server", PROGRAM_NAME);
response.append_header("Date", get_current_date_GMT());
response.append_header("Content-Type", "text/html");
response.append_header("Content-Length", std::to_string(response.get_body_size()));
response.append_header("Connection", "keep-alive");
response.append_header("Location", client.server->redirect_url);

`위와 같이 넣었음에도, 커넥션 - 콘텐트랭스 - 콘텐트 타입 - 데이트 - 로케이션 - 서버 순으로 맵에서 뽑아내서 헤더를 만들고 있습니다.

4. 헤더 첫라인 만들 때 상태코드만 들어와야 하는데, status를 보니 Response Phrase 까지 모두 들어와서 헤더안에 들어갑니다.
문제는 이거... status.substr(0,3)으로 상태넘버만 넣어서 할려고 했는데도 실제 응답에서는 status 전체가 들어왔었습니다. (substr가 안먹힘..)

5. response 객체의 응답 메세지를 만들어 줄 때 make_body 함수가 또 생겼는데, make_error_body랑 make_redirection_body랑 통합하는 것도 나쁘지는 않아보입니다.

**Comment by mocha-kim** [comment]
2번 4번 제가 가져갑니도~~!

**Comment by Two-Jay** [comment]
3,5 가져갑니도~~!

**Comment by mocha-kim** [comment]
2, 4번 해결했습니다~~ 동일한 문제 생기면 알려주세욥

**Comment by Two-Jay** [comment]
3번은 수정 안하기로 했고
1번도 마찬가지
5번은 수정했습니다~
